In [2]:
import pandas as pd
# from URL
dfs = pd.read_html("https://docs.google.com/spreadsheets/d/e/2PACX-1vQlEs3FxFPwm-dpvU1YdsfRgsbfT9WdiXJHZm9kJgGTziPnk-y3TWtftbSbxj6Fe_g0NxYgqyVHTVU5/pubhtml?gid=1397577608&amp;single=true&amp;widget=true&amp;headers=false")
dfs

[    Unnamed: 0         Unnamed: 1   Unnamed: 2         Unnamed: 3  \
 0            1        retrived_at  province_id               city
 1            2   5/1/2023 9:15:27        TH-10        Phra Nakhon
 2            3   5/1/2023 9:15:58        TH-11          Bang Phli
 3            4   5/1/2023 9:16:28        TH-12  Mueang Nonthaburi
 4            5   5/1/2023 9:16:59        TH-13       Khlong Luang
 ..         ...                ...          ...                ...
 62          63  5/1/2023 14:18:34        TH-16             Ban Mi
 63          64  5/1/2023 14:19:05        TH-20           Na Kluea
 64          65  5/1/2023 14:19:36        TH-21           Ban Khai
 65          66  5/1/2023 14:20:07        TH-50         Chiang Mai
 66          67  5/1/2023 14:20:38        TH-52          Hang Chat

       Unnamed: 4 Unnamed: 5     Unnamed: 6     Unnamed: 7  Unnamed: 8  \
 0          state    country  pollution_aqi  polution_main  weather_tp
 1        Bangkok   Thailand             78             p2          28
 2   Samut Prakan   Thailand             90             p2          29
 3     Nonthaburi   Thailand            105             p2          29
 4   Pathum Thani   Thailand             89             p2          30
 ..           ...        ...            ...            ...         ...
 62      Lop Buri   Thailand             66             p2          39
 63     Chon Buri   Thailand             85             p2          33
 64        Rayong   Thailand             72             p2          33
 65    Chiang Mai   Thailand             78             p2          37
 66       Lampang   Thailand             97             p2          38

     Unnamed: 9 Unnamed: 10 Unnamed: 11 Unnamed: 12
 0   weather_pr  weather_hu  weather_ws  weather_wd
 1         1010          56        2.16          90
 2         1010          70        2.57          50
 3         1011          75        3.09          80
 4         1011          83        3.09          80
 ..         ...         ...         ...         ...
 62        1006          32        0.85         153
 63        1007          61        2.78         240
 64        1009          61        3.45         184
 65         990          39        2.57           0
 66        1007          40         0.4         165

 [67 rows x 13 columns]]

In [3]:
df=dfs[0]
df

,Unnamed: 0,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10,Unnamed: 11,Unnamed: 12
0,1,retrived_at,province_id,city,state,country,pollution_aqi,polution_main,weather_tp,weather_pr,weather_hu,weather_ws,weather_wd
1,2,5/1/2023 9:15:27,TH-10,Phra Nakhon,Bangkok,Thailand,78,p2,28,1010,56,2.16,90
2,3,5/1/2023 9:15:58,TH-11,Bang Phli,Samut Prakan,Thailand,90,p2,29,1010,70,2.57,50
3,4,5/1/2023 9:16:28,TH-12,Mueang Nonthaburi,Nonthaburi,Thailand,105,p2,29,1011,75,3.09,80
4,5,5/1/2023 9:16:59,TH-13,Khlong Luang,Pathum Thani,Thailand,89,p2,30,1011,83,3.09,80
...,...,...,...,...,...,...,...,...,...,...,...,...,...
62,63,5/1/2023 14:18:34,TH-16,Ban Mi,Lop Buri,Thailand,66,p2,39,1006,32,0.85,153
63,64,5/1/2023 14:19:05,TH-20,Na Kluea,Chon Buri,Thailand,85,p2,33,1007,61,2.78,240
64,65,5/1/2023 14:19:36,TH-21,Ban Khai,Rayong,Thailand,72,p2,33,1009,61,3.45,184
65,66,5/1/2023 14:20:07,TH-50,Chiang Mai,Chiang Mai,Thailand,78,p2,37,990,39,2.57,0
66,67,5/1/2023 14:20:38,TH-52,Hang Chat,Lampang,Thailand,97,p2,38,1007,40,0.4,165

In [4]:
df.columns = df.iloc[0]
df

,1,retrived_at,province_id,city,state,country,pollution_aqi,polution_main,weather_tp,weather_pr,weather_hu,weather_ws,weather_wd
0,1,retrived_at,province_id,city,state,country,pollution_aqi,polution_main,weather_tp,weather_pr,weather_hu,weather_ws,weather_wd
1,2,5/1/2023 9:15:27,TH-10,Phra Nakhon,Bangkok,Thailand,78,p2,28,1010,56,2.16,90
2,3,5/1/2023 9:15:58,TH-11,Bang Phli,Samut Prakan,Thailand,90,p2,29,1010,70,2.57,50
3,4,5/1/2023 9:16:28,TH-12,Mueang Nonthaburi,Nonthaburi,Thailand,105,p2,29,1011,75,3.09,80
4,5,5/1/2023 9:16:59,TH-13,Khlong Luang,Pathum Thani,Thailand,89,p2,30,1011,83,3.09,80
...,...,...,...,...,...,...,...,...,...,...,...,...,...
62,63,5/1/2023 14:18:34,TH-16,Ban Mi,Lop Buri,Thailand,66,p2,39,1006,32,0.85,153
63,64,5/1/2023 14:19:05,TH-20,Na Kluea,Chon Buri,Thailand,85,p2,33,1007,61,2.78,240
64,65,5/1/2023 14:19:36,TH-21,Ban Khai,Rayong,Thailand,72,p2,33,1009,61,3.45,184
65,66,5/1/2023 14:20:07,TH-50,Chiang Mai,Chiang Mai,Thailand,78,p2,37,990,39,2.57,0
66,67,5/1/2023 14:20:38,TH-52,Hang Chat,Lampang,Thailand,97,p2,38,1007,40,0.4,165

In [5]:
df = df[1:]
df

,1,retrived_at,province_id,city,state,country,pollution_aqi,polution_main,weather_tp,weather_pr,weather_hu,weather_ws,weather_wd
1,2,5/1/2023 9:15:27,TH-10,Phra Nakhon,Bangkok,Thailand,78,p2,28,1010,56,2.16,90
2,3,5/1/2023 9:15:58,TH-11,Bang Phli,Samut Prakan,Thailand,90,p2,29,1010,70,2.57,50
3,4,5/1/2023 9:16:28,TH-12,Mueang Nonthaburi,Nonthaburi,Thailand,105,p2,29,1011,75,3.09,80
4,5,5/1/2023 9:16:59,TH-13,Khlong Luang,Pathum Thani,Thailand,89,p2,30,1011,83,3.09,80
5,6,5/1/2023 9:17:31,TH-14,Ayutthaya,Phra Nakhon Si Ayutthaya,Thailand,133,p2,30,1010,59,1.65,107
...,...,...,...,...,...,...,...,...,...,...,...,...,...
62,63,5/1/2023 14:18:34,TH-16,Ban Mi,Lop Buri,Thailand,66,p2,39,1006,32,0.85,153
63,64,5/1/2023 14:19:05,TH-20,Na Kluea,Chon Buri,Thailand,85,p2,33,1007,61,2.78,240
64,65,5/1/2023 14:19:36,TH-21,Ban Khai,Rayong,Thailand,72,p2,33,1009,61,3.45,184
65,66,5/1/2023 14:20:07,TH-50,Chiang Mai,Chiang Mai,Thailand,78,p2,37,990,39,2.57,0
66,67,5/1/2023 14:20:38,TH-52,Hang Chat,Lampang,Thailand,97,p2,38,1007,40,0.4,165

In [6]:
df = df.drop(columns=[1])
df

,retrived_at,province_id,city,state,country,pollution_aqi,polution_main,weather_tp,weather_pr,weather_hu,weather_ws,weather_wd
1,5/1/2023 9:15:27,TH-10,Phra Nakhon,Bangkok,Thailand,78,p2,28,1010,56,2.16,90
2,5/1/2023 9:15:58,TH-11,Bang Phli,Samut Prakan,Thailand,90,p2,29,1010,70,2.57,50
3,5/1/2023 9:16:28,TH-12,Mueang Nonthaburi,Nonthaburi,Thailand,105,p2,29,1011,75,3.09,80
4,5/1/2023 9:16:59,TH-13,Khlong Luang,Pathum Thani,Thailand,89,p2,30,1011,83,3.09,80
5,5/1/2023 9:17:31,TH-14,Ayutthaya,Phra Nakhon Si Ayutthaya,Thailand,133,p2,30,1010,59,1.65,107
...,...,...,...,...,...,...,...,...,...,...,...,...
62,5/1/2023 14:18:34,TH-16,Ban Mi,Lop Buri,Thailand,66,p2,39,1006,32,0.85,153
63,5/1/2023 14:19:05,TH-20,Na Kluea,Chon Buri,Thailand,85,p2,33,1007,61,2.78,240
64,5/1/2023 14:19:36,TH-21,Ban Khai,Rayong,Thailand,72,p2,33,1009,61,3.45,184
65,5/1/2023 14:20:07,TH-50,Chiang Mai,Chiang Mai,Thailand,78,p2,37,990,39,2.57,0
66,5/1/2023 14:20:38,TH-52,Hang Chat,Lampang,Thailand,97,p2,38,1007,40,0.4,165

In [ ]:
df.to_csv("df.csv",index=False)